site_name: Docpart 1C API
nav:
    - Описание: index.md
    - Установка: install.md
    - Методы API: methods.md
        - Общего назначения: common_methods.md
        - Заказы: order_methods.md
        - Оплаты: payment_methods.md
        - Клиенты: users_methods.md
        - Каталог товаров: cat_methods.md
    - Примеры использования: samples.md
theme: readthedocs
